layout_spectrum: 0.06998314
name: SEO Website Marketing
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.8541315
color:
  brandStrength: 0.9367622
  lightness: 0.7563238
  saturation: 1
  rhythmicContrast: 0.7209106
  brandColors:
    - '#000000'
    - '#664428'
    - '#95969A'
    - '#DD9A25'
    - '#E9207A'
