layout_spectrum: 1
typography_spectrum: 1
color:
  lightness: 0.8619573
  brandStrength: 0.6871838
  saturation: 0.7094929
  rhythmicContrast: 0.6266126
  brandColors:
    - '#000000'
    - '#664428'
    - '#95969A'
    - '#DD9A25'
    - '#E9207A'
name: SEO Website Marketing
