layout_spectrum: 0.5087609
name: SEO Website Marketing
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.1483104
color:
  brandStrength: 0.9367622
  lightness: 0.8441802
  saturation: 1
  rhythmicContrast: 1
  brandColors:
    - '#000000'
    - '#664428'
    - '#95969A'
    - '#DD9A25'
    - '#E9207A'
